#pragma checksum "..\..\NavaliSettingsGui.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7F7C0528F95C7CFE5D95CDE5CDB10E56"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MahApps.Metro.Controls;
using Navali;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Navali {
    
    
    /// <summary>
    /// NavaliSettingsGui
    /// </summary>
    public partial class NavaliSettingsGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Root;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox m1;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox m2;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c1;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c2;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c3;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c4;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c5;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c6;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c7;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c8;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c9;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c10;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c11;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox c12;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f1;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f2;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f3;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f4;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f5;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f6;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f7;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f8;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f9;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f10;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f11;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f12;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f13;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f14;
        
        #line default
        #line hidden
        
        
        #line 170 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f15;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f16;
        
        #line default
        #line hidden
        
        
        #line 172 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f17;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f18;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f19;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f20;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f21;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f22;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f23;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f24;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox f25;
        
        #line default
        #line hidden
        
        
        #line 288 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e0;
        
        #line default
        #line hidden
        
        
        #line 289 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e1;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e2;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e3;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e4;
        
        #line default
        #line hidden
        
        
        #line 293 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e5;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e6;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e7;
        
        #line default
        #line hidden
        
        
        #line 296 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e8;
        
        #line default
        #line hidden
        
        
        #line 297 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e9;
        
        #line default
        #line hidden
        
        
        #line 298 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e10;
        
        #line default
        #line hidden
        
        
        #line 299 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e11;
        
        #line default
        #line hidden
        
        
        #line 300 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e12;
        
        #line default
        #line hidden
        
        
        #line 301 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e13;
        
        #line default
        #line hidden
        
        
        #line 302 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e14;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e15;
        
        #line default
        #line hidden
        
        
        #line 304 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e16;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e17;
        
        #line default
        #line hidden
        
        
        #line 306 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e18;
        
        #line default
        #line hidden
        
        
        #line 307 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e19;
        
        #line default
        #line hidden
        
        
        #line 308 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e20;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e21;
        
        #line default
        #line hidden
        
        
        #line 310 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e22;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e23;
        
        #line default
        #line hidden
        
        
        #line 312 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e24;
        
        #line default
        #line hidden
        
        
        #line 313 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e25;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e26;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e27;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e28;
        
        #line default
        #line hidden
        
        
        #line 317 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e29;
        
        #line default
        #line hidden
        
        
        #line 318 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e30;
        
        #line default
        #line hidden
        
        
        #line 319 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e31;
        
        #line default
        #line hidden
        
        
        #line 320 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e32;
        
        #line default
        #line hidden
        
        
        #line 321 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e33;
        
        #line default
        #line hidden
        
        
        #line 322 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e34;
        
        #line default
        #line hidden
        
        
        #line 323 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e35;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e36;
        
        #line default
        #line hidden
        
        
        #line 325 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e37;
        
        #line default
        #line hidden
        
        
        #line 326 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e38;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e39;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e40;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e41;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e42;
        
        #line default
        #line hidden
        
        
        #line 331 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e43;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e44;
        
        #line default
        #line hidden
        
        
        #line 333 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e45;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e46;
        
        #line default
        #line hidden
        
        
        #line 335 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox e47;
        
        #line default
        #line hidden
        
        
        #line 359 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s0;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s1;
        
        #line default
        #line hidden
        
        
        #line 361 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s2;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s3;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s4;
        
        #line default
        #line hidden
        
        
        #line 364 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox s5;
        
        #line default
        #line hidden
        
        
        #line 462 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n0;
        
        #line default
        #line hidden
        
        
        #line 463 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n1;
        
        #line default
        #line hidden
        
        
        #line 464 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n2;
        
        #line default
        #line hidden
        
        
        #line 465 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n3;
        
        #line default
        #line hidden
        
        
        #line 466 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n4;
        
        #line default
        #line hidden
        
        
        #line 467 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n5;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n6;
        
        #line default
        #line hidden
        
        
        #line 469 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n7;
        
        #line default
        #line hidden
        
        
        #line 470 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n8;
        
        #line default
        #line hidden
        
        
        #line 471 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n9;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n10;
        
        #line default
        #line hidden
        
        
        #line 473 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n11;
        
        #line default
        #line hidden
        
        
        #line 474 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n12;
        
        #line default
        #line hidden
        
        
        #line 475 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n13;
        
        #line default
        #line hidden
        
        
        #line 476 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n14;
        
        #line default
        #line hidden
        
        
        #line 477 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n15;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n16;
        
        #line default
        #line hidden
        
        
        #line 479 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n17;
        
        #line default
        #line hidden
        
        
        #line 480 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n18;
        
        #line default
        #line hidden
        
        
        #line 481 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n19;
        
        #line default
        #line hidden
        
        
        #line 482 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n20;
        
        #line default
        #line hidden
        
        
        #line 483 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n21;
        
        #line default
        #line hidden
        
        
        #line 484 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n22;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n23;
        
        #line default
        #line hidden
        
        
        #line 486 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n24;
        
        #line default
        #line hidden
        
        
        #line 487 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n25;
        
        #line default
        #line hidden
        
        
        #line 488 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n26;
        
        #line default
        #line hidden
        
        
        #line 489 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n27;
        
        #line default
        #line hidden
        
        
        #line 490 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n28;
        
        #line default
        #line hidden
        
        
        #line 491 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n29;
        
        #line default
        #line hidden
        
        
        #line 492 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n30;
        
        #line default
        #line hidden
        
        
        #line 493 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n31;
        
        #line default
        #line hidden
        
        
        #line 494 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n32;
        
        #line default
        #line hidden
        
        
        #line 495 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n33;
        
        #line default
        #line hidden
        
        
        #line 496 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n34;
        
        #line default
        #line hidden
        
        
        #line 497 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n35;
        
        #line default
        #line hidden
        
        
        #line 498 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n36;
        
        #line default
        #line hidden
        
        
        #line 499 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n37;
        
        #line default
        #line hidden
        
        
        #line 500 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n38;
        
        #line default
        #line hidden
        
        
        #line 501 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n39;
        
        #line default
        #line hidden
        
        
        #line 502 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n40;
        
        #line default
        #line hidden
        
        
        #line 503 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n41;
        
        #line default
        #line hidden
        
        
        #line 504 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox n42;
        
        #line default
        #line hidden
        
        
        #line 528 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o0;
        
        #line default
        #line hidden
        
        
        #line 529 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o1;
        
        #line default
        #line hidden
        
        
        #line 530 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o2;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o3;
        
        #line default
        #line hidden
        
        
        #line 532 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o4;
        
        #line default
        #line hidden
        
        
        #line 533 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox o5;
        
        #line default
        #line hidden
        
        
        #line 649 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p0;
        
        #line default
        #line hidden
        
        
        #line 650 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p1;
        
        #line default
        #line hidden
        
        
        #line 651 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p2;
        
        #line default
        #line hidden
        
        
        #line 652 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p3;
        
        #line default
        #line hidden
        
        
        #line 653 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p4;
        
        #line default
        #line hidden
        
        
        #line 654 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p5;
        
        #line default
        #line hidden
        
        
        #line 655 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p6;
        
        #line default
        #line hidden
        
        
        #line 656 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p7;
        
        #line default
        #line hidden
        
        
        #line 657 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p8;
        
        #line default
        #line hidden
        
        
        #line 658 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p9;
        
        #line default
        #line hidden
        
        
        #line 659 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p10;
        
        #line default
        #line hidden
        
        
        #line 660 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p11;
        
        #line default
        #line hidden
        
        
        #line 661 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p12;
        
        #line default
        #line hidden
        
        
        #line 662 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p13;
        
        #line default
        #line hidden
        
        
        #line 663 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p14;
        
        #line default
        #line hidden
        
        
        #line 664 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p15;
        
        #line default
        #line hidden
        
        
        #line 665 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p16;
        
        #line default
        #line hidden
        
        
        #line 666 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p17;
        
        #line default
        #line hidden
        
        
        #line 667 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p18;
        
        #line default
        #line hidden
        
        
        #line 668 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p19;
        
        #line default
        #line hidden
        
        
        #line 669 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p20;
        
        #line default
        #line hidden
        
        
        #line 670 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p21;
        
        #line default
        #line hidden
        
        
        #line 671 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p22;
        
        #line default
        #line hidden
        
        
        #line 672 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p23;
        
        #line default
        #line hidden
        
        
        #line 673 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p24;
        
        #line default
        #line hidden
        
        
        #line 674 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p25;
        
        #line default
        #line hidden
        
        
        #line 675 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p26;
        
        #line default
        #line hidden
        
        
        #line 676 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p27;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p28;
        
        #line default
        #line hidden
        
        
        #line 678 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p29;
        
        #line default
        #line hidden
        
        
        #line 679 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p30;
        
        #line default
        #line hidden
        
        
        #line 680 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p31;
        
        #line default
        #line hidden
        
        
        #line 681 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p32;
        
        #line default
        #line hidden
        
        
        #line 682 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p33;
        
        #line default
        #line hidden
        
        
        #line 683 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p34;
        
        #line default
        #line hidden
        
        
        #line 684 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p35;
        
        #line default
        #line hidden
        
        
        #line 685 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p36;
        
        #line default
        #line hidden
        
        
        #line 686 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p37;
        
        #line default
        #line hidden
        
        
        #line 687 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p38;
        
        #line default
        #line hidden
        
        
        #line 688 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p39;
        
        #line default
        #line hidden
        
        
        #line 689 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p40;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p41;
        
        #line default
        #line hidden
        
        
        #line 691 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p42;
        
        #line default
        #line hidden
        
        
        #line 692 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p43;
        
        #line default
        #line hidden
        
        
        #line 693 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p44;
        
        #line default
        #line hidden
        
        
        #line 694 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p45;
        
        #line default
        #line hidden
        
        
        #line 695 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p46;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p47;
        
        #line default
        #line hidden
        
        
        #line 697 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p48;
        
        #line default
        #line hidden
        
        
        #line 698 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p49;
        
        #line default
        #line hidden
        
        
        #line 699 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p50;
        
        #line default
        #line hidden
        
        
        #line 700 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox p51;
        
        #line default
        #line hidden
        
        
        #line 724 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t0;
        
        #line default
        #line hidden
        
        
        #line 725 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t1;
        
        #line default
        #line hidden
        
        
        #line 726 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t2;
        
        #line default
        #line hidden
        
        
        #line 727 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t3;
        
        #line default
        #line hidden
        
        
        #line 728 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t4;
        
        #line default
        #line hidden
        
        
        #line 729 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox t5;
        
        #line default
        #line hidden
        
        
        #line 757 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x0;
        
        #line default
        #line hidden
        
        
        #line 758 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x1;
        
        #line default
        #line hidden
        
        
        #line 759 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x2;
        
        #line default
        #line hidden
        
        
        #line 760 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x3;
        
        #line default
        #line hidden
        
        
        #line 761 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x4;
        
        #line default
        #line hidden
        
        
        #line 762 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x5;
        
        #line default
        #line hidden
        
        
        #line 763 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x6;
        
        #line default
        #line hidden
        
        
        #line 764 "..\..\NavaliSettingsGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox x7;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Navali;component/navalisettingsgui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\NavaliSettingsGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.m1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.m2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.c1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.c2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.c3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.c4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.c5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.c6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 10:
            this.c7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.c8 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.c9 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.c10 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 14:
            this.c11 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 15:
            this.c12 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.f1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.f2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 18:
            this.f3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.f4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 20:
            this.f5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 21:
            this.f6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 22:
            this.f7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 23:
            this.f8 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 24:
            this.f9 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.f10 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 26:
            this.f11 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 27:
            this.f12 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 28:
            this.f13 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 29:
            this.f14 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 30:
            this.f15 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 31:
            this.f16 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 32:
            this.f17 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 33:
            this.f18 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 34:
            this.f19 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 35:
            this.f20 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 36:
            this.f21 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 37:
            this.f22 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 38:
            this.f23 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 39:
            this.f24 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 40:
            this.f25 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 41:
            this.e0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 42:
            this.e1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 43:
            this.e2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 44:
            this.e3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 45:
            this.e4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 46:
            this.e5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 47:
            this.e6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 48:
            this.e7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 49:
            this.e8 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 50:
            this.e9 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 51:
            this.e10 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 52:
            this.e11 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 53:
            this.e12 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 54:
            this.e13 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 55:
            this.e14 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 56:
            this.e15 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 57:
            this.e16 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 58:
            this.e17 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 59:
            this.e18 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 60:
            this.e19 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 61:
            this.e20 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 62:
            this.e21 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 63:
            this.e22 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 64:
            this.e23 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 65:
            this.e24 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 66:
            this.e25 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 67:
            this.e26 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 68:
            this.e27 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 69:
            this.e28 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 70:
            this.e29 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 71:
            this.e30 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 72:
            this.e31 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 73:
            this.e32 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 74:
            this.e33 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 75:
            this.e34 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 76:
            this.e35 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 77:
            this.e36 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 78:
            this.e37 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 79:
            this.e38 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 80:
            this.e39 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 81:
            this.e40 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 82:
            this.e41 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 83:
            this.e42 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 84:
            this.e43 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 85:
            this.e44 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 86:
            this.e45 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 87:
            this.e46 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 88:
            this.e47 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 89:
            this.s0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 90:
            this.s1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 91:
            this.s2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 92:
            this.s3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 93:
            this.s4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 94:
            this.s5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 95:
            this.n0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 96:
            this.n1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 97:
            this.n2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 98:
            this.n3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 99:
            this.n4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 100:
            this.n5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 101:
            this.n6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 102:
            this.n7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 103:
            this.n8 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 104:
            this.n9 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 105:
            this.n10 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 106:
            this.n11 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 107:
            this.n12 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 108:
            this.n13 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 109:
            this.n14 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 110:
            this.n15 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 111:
            this.n16 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 112:
            this.n17 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 113:
            this.n18 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 114:
            this.n19 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 115:
            this.n20 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 116:
            this.n21 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 117:
            this.n22 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 118:
            this.n23 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 119:
            this.n24 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 120:
            this.n25 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 121:
            this.n26 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 122:
            this.n27 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 123:
            this.n28 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 124:
            this.n29 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 125:
            this.n30 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 126:
            this.n31 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 127:
            this.n32 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 128:
            this.n33 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 129:
            this.n34 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 130:
            this.n35 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 131:
            this.n36 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 132:
            this.n37 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 133:
            this.n38 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 134:
            this.n39 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 135:
            this.n40 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 136:
            this.n41 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 137:
            this.n42 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 138:
            this.o0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 139:
            this.o1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 140:
            this.o2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 141:
            this.o3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 142:
            this.o4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 143:
            this.o5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 144:
            this.p0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 145:
            this.p1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 146:
            this.p2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 147:
            this.p3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 148:
            this.p4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 149:
            this.p5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 150:
            this.p6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 151:
            this.p7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 152:
            this.p8 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 153:
            this.p9 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 154:
            this.p10 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 155:
            this.p11 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 156:
            this.p12 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 157:
            this.p13 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 158:
            this.p14 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 159:
            this.p15 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 160:
            this.p16 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 161:
            this.p17 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 162:
            this.p18 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 163:
            this.p19 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 164:
            this.p20 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 165:
            this.p21 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 166:
            this.p22 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 167:
            this.p23 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 168:
            this.p24 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 169:
            this.p25 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 170:
            this.p26 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 171:
            this.p27 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 172:
            this.p28 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 173:
            this.p29 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 174:
            this.p30 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 175:
            this.p31 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 176:
            this.p32 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 177:
            this.p33 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 178:
            this.p34 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 179:
            this.p35 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 180:
            this.p36 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 181:
            this.p37 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 182:
            this.p38 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 183:
            this.p39 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 184:
            this.p40 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 185:
            this.p41 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 186:
            this.p42 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 187:
            this.p43 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 188:
            this.p44 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 189:
            this.p45 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 190:
            this.p46 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 191:
            this.p47 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 192:
            this.p48 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 193:
            this.p49 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 194:
            this.p50 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 195:
            this.p51 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 196:
            this.t0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 197:
            this.t1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 198:
            this.t2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 199:
            this.t3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 200:
            this.t4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 201:
            this.t5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 202:
            this.x0 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 203:
            this.x1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 204:
            this.x2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 205:
            this.x3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 206:
            this.x4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 207:
            this.x5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 208:
            this.x6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 209:
            this.x7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

